FROM centos:7

COPY ./src/ /src/

WORKDIR /src

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*.repo \
    && sed -i 's|#baseurl=http://mirror.centos.org/centos|baseurl=https://mirrors.aliyun.com/centos|g' /etc/yum.repos.d/CentOS-*.repo \
    && sed -i 's|baseurl=http://mirror.centos.org/centos|baseurl=https://mirrors.aliyun.com/centos|g' /etc/yum.repos.d/CentOS-*.repo \
    && yum clean all \
    && yum makecache 

RUN yum install -y gcc make unzip elfutils-libelf-devel

    # 需要根据实际的内核版本修改此处
RUN yum localinstall -y kernel-3.10.0-1160.el7.x86_64.rpm \
    && yum localinstall -y kernel-devel-3.10.0-1160.el7.x86_64.rpm

RUN tar -xzvf libdwarf-20201201.tar.gz \
    && cd libdwarf-20201201 \
    && chmod +x * \
    && ./configure \
    && make install \
    && cd .. \
    && unzip tools.zip \
    && cd /src/tools/linux \
    && echo 'MODULE_LICENSE("GPL");' >> module.c \
    # 需要根据实际的内核版本修改此处
    && sed -i 's/$(shell uname -r)/3.10.0-1160.el7.x86_64/g' Makefile \
    && make \
    && mv module.dwarf /tmp/module.dwarf

# 清理 yum 缓存以减小镜像体积
RUN yum clean all